config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
    resources :orders, only: [:new, :create]
    # , :only => [:show, :update, :edit]
    member do
      put "like", to: "pins#upvote"
    end
  end

  match '/seller' => "pins#seller", via: :get, as: :seller
  match '/sales' => "orders#sales", via: :get, as: :sales
  match '/purchases' => "orders#purchases", via: :get, as: :purchases

 root "pins#index"
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :pin
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"

  attr_accessor :card_number, :card_cvc, :card_expires_month, :card_expires_year, :card_holder

  validates :address, :city, :state, :zip_code, presence: true
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  acts_as_votable
  has_many :orders
  belongs_to :user

  # if Rails.env.development?
  #   has_attached_file :image, styles: { medium: '250x', thumb: '150x' }, default_url: 'default.jpg'
  # else
    has_attached_file :image, styles: { medium: '250x', thumb: '150x' }, default_url: 'default.jpg'
  # end



  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  attr_accessor :countries, :routing_number, :account_number

  validates :title, :description, :image, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /orders
  # GET /orders.json

  def sales
    @orders = Order.all.where(seller: current_user).order('created_at DESC')
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order('created_at DESC')
  end

  # GET /orders/new
  def new
    @order = Order.new
    @pin = Pin.find(params[:pin_id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @pin = Pin.find(params[:pin_id])
    @seller = @pin.user

    @order.buyer_id = current_user.id
    @order.pin_id = @pin.id
    @order.seller_id = @seller.id

    Stripe.api_key = ENV['STRIPE_API_KEY']
    token = params[:stripeToken]

    begin
      charge = Stripe::Charge.create(
        amount: (@pin.price * 100).floor,
        currency: "usd",
        card: token
      )
      flash[:notice] = 'Thanks for ordering'
    rescue Stripe::CardError => e
      flash[:danger] = e.message
    end

    transfer = Stripe::Transfer.create(
      :amount => (@pin.price * 95).floor,
      :currency => "usd",
      :destination => @seller.recipient
    )

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:address, :city, :state, :zip_code)
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:destroy, :update, :edit]

  def index
    @pins = Pin.all.order('created_at DESC')
  end

  def seller
    @pins = Pin.where(user: current_user).order('created_at DESC')
  end

  def new
    @pin = Pin.new
  end

  def create
    @pin = Pin.new(pin_params)
    @pin.user = current_user

    if current_user.recipient.blank?

      Stripe.api_key = ENV['STRIPE_API_KEY']
      token = params[:stripeToken]

      recipient = Stripe::Account.create(
        {
          :country => "US",
          :managed => true
        }
      )

      account = Stripe::Account.retrieve(recipient.id)


      account.external_accounts.create({
        :bank_account => token
      })

    end

    current_user.recipient = recipient
    current_user.save

    if @pin.save
      redirect_to @pin, notice: 'Successfully created new Pin!'
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was Successfully updated!'
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to :back
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :price, :description, :image)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end

  def check_user
    if current_user != @pin.user
      redirect_to root_url, alert: 'Sorry, this pin belongs to someone else'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-brand= link_to "Bin Board", root_path

    - if user_signed_in?
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "New Pin", new_pin_path
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Seller
            %span.caret
          %ul.dropdown-menu
            %li= link_to "Manage Pins", seller_path
            %li= link_to "Sales History", sales_path

        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Account
            %span.caret
          %ul.dropdown-menu
            %li= link_to "Account", edit_user_registration_path
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
            %li.divider{:role => "separator"}
            %li= link_to "Purchase History", purchases_path




    - else
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Sign Up", new_user_registration_path
        %li= link_to "Sign In", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Bin Board"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "https://js.stripe.com/v2/"
    = javascript_include_tag "application"
    = tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"]
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  %body
    = render "layouts/navbar"
    .container
      .row
        - flash.each do |name, msg|
          =content_tag  :div, msg, class: "alert alert-info"
        = yield
      %footer
        %p © Tom 2017

app/views/orders/_form.html.haml
.row
  .col-md-4
    .thumbnail
      = image_tag @pin.image.url
      %h3
        = @pin.title
      %h4=number_to_currency(@pin.price)
  .col-md-8
    = simple_form_for([@pin, @order], id: 'new_order' ) do |f|
      = f.error_notification
      #stripe_error.alert.alert-danger{:style => "display: none"}
        %noscript
          Javascript is required for this form, Please enable it in your browser setting
      .form-inputs
        = f.input :address
        = f.input :city
        = f.input :state
        = f.input :zip_code
        -# = f.input :card_holder, :label => "Cardholder", :placeholder => "Full Name", :input_html => {:autocomplete => :off, :size => 20, :id => "card-name", :name => nil, :'data-stripe' => "card_holder"}, :class => "pull-left"
        .row
          = f.input :card_number, :label => "Card Number", :input_html => {:autocomplete => :off, :size => 20, :id => "card-number", :name => nil, :'data-stripe' => "number"}, wrapper_html: { class: 'col-md-9' }
          = f.input :card_cvc, :label => "CVC", :placeholder => "This 3- or 4-digit code is usually found on the back of your credit card", :input_html => {:autocomplete => :off, :size => 20, :id => "card_cvc", :name => nil ,:'data-stripe' => "cvv"}, wrapper_html: { class: 'col-md-3' }
        .control-group.string.required
          %label.string.required.control-label{:for => "card-expiry-month"}
            %abbr{:title => "required"}*
            Expiration Date
        .controls.row
          .col-md-6
            = select_month nil, { user_two_digit_numbers: true}, {:name => nil, :'data-stripe' => "exp-month", class: "form-control"}
          .col-md-6
            = select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :'data-stripe' => "exp-year", class: "form-control" }
      %br
      .form-actions
        = f.button :submit

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', pin_orders_path %>

app/views/orders/purchases.html.haml
.text-center
  %h1
    %strong
      = "#{current_user.first_name.capitalize} #{current_user.last_name.capitalize[0]}. Purchase history"
.table-responsive
  %table.table.table-hover.table-condensed
    %thead
      %tr
        %th Image
        %th Item
        %th Price
        %th Seller
        %th Date Sold
    %tbody
      - @orders.each do |order|
        %tr
          %td= link_to (image_tag order.pin.image.url(:thumb))
          %td= order.pin.title
          %td= number_to_currency(order.pin.price)
          %td= "#{order.seller.first_name.capitalize} #{order.seller.last_name.capitalize[0]}."
          %td= order.created_at.strftime("%B %-d, %Y")





  %br/

app/views/orders/sales.html.haml
.text-center
  %h1
    %strong
      = "#{current_user.first_name.capitalize} #{current_user.last_name.capitalize[0]}. Sales history"
.table-responsive
  %table.table.table-hover.table-condensed
    %thead
      %tr
        %th Image
        %th Item
        %th Price
        %th Customer
        %th Date Sold
    %tbody
      - @orders.each do |order|
        %tr
          %td= link_to (image_tag order.pin.image.url(:thumb))
          %td= order.pin.title
          %td= number_to_currency(order.pin.price)
          %td= "#{order.buyer.first_name.capitalize} #{order.buyer.last_name.capitalize[0]}."
          %td= order.created_at.strftime("%B %-d, %Y")





  %br/

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
  - if @pin.errors.any?
    #errors.alert.alert-danger.alert-dissmissable
      %h2
      = pluralize(@pin.errors.count, "error")
      prevented this Pin from saving
      %ul
        -@pin.errors.full_messages.each do |msg|
          %li= msg
  #stripe_error.alert.alert-danger{:style => "display: none"}
    %noscript
      Javascript is required for this form, Please enable it in your browser setting
  .form-group
    = f.input :title, input_html: {class: 'form-control'}

  .form-group
    = f.input :price, input_html: {class: 'form-control'}

  .form-group
    = f.input :image, input_html: {class: 'form-control'}

  .form-group
    = f.input :description, input_html: {class: 'form control'}


  - if current_user.recipient.blank?
    %br
    %h1
      Bank Account Info

    .form-group
      = f.input :countries, :label => "Country", :input_html => {:autocomplete => :off, :size => 20, :id => "country", :name => nil, :'data-stripe' => "country", class: 'form-control' }

    .form-group
      = f.input :routing_number, :label => "Routing Number", :input_html => {:autocomplete => :off, :size => 20, :id => "routing-number", :name => nil, :'data-stripe' => "routingNumber", class: 'form-control' }

    .form-group
      = f.input :account_number, :label => "Account Number", :input_html => {:autocomplete => :off, :size => 20, :id => "account-number", :name => nil, :'data-stripe' => "accountNumber", class: 'form-control' }


  = f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit Pin
      .panel-body
        %strong.center Current Image
        = image_tag @pin.image.url(:medium)
        = render 'form'
        = link_to "Cancel", pin_path

app/views/pins/index.html.haml
.col-md-12
  #pins.transitions-enabled
    - @pins.each do |pin|
      .box.panel.panel-default
        = link_to (image_tag pin.image.url(:medium)), pin
        .panel-body
          %h2= link_to pin.title, pin
          %p.user
          Submitted by
          = "#{pin.user.first_name.capitalize} #{pin.user.last_name.capitalize[0]}."

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 New Form
      .panel-body
        = render 'form'
        = link_to 'Back', root_path

app/views/pins/seller.html.haml
.table-responsive
  %table.table.table-hover.table-condensed
    %thead
      %tr
        %th Image
        %th Title
        %th Description
        %th Price
        %th Action
        - if user_signed_in?
          %th{:colspan => "1"}
    %tbody
      - @pins.each do |pin|
        %tr
          %td= link_to (image_tag pin.image.url(:thumb)), pin
          %td= pin.title
          %td= pin.description
          %td= number_to_currency(pin.price)
          - if user_signed_in?
            %td
              .btn-group
                %button.btn.btn-primary.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
                  Action
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to 'Show', pin_path(pin)
                  %li= link_to 'Edit', edit_pin_path(pin)
                  %li= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }







  %br/

- if user_signed_in?
  = link_to 'New Pin', new_pin_path, class: "btn btn-info"

app/views/pins/show.html.haml
#pin_show
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.pin_image
        = image_tag @pin.image.url
      .panel-body
        %h1= @pin.title
        %h3= number_to_currency(@pin.price)
        %p.description= @pin.description
        - unless (@pin.user == current_user)
          = link_to "Buy It Now", new_pin_order_path(@pin), class: "btn btn-primary"
      .panel-footer
        .row
          .col-md-6
            %p.user
            Submitted by
            = "#{@pin.user.first_name.capitalize} #{@pin.user.last_name.capitalize[0]}."
          .col-md-6
            .btn-group.pull-right
              = link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-heart
                  = @pin.get_upvotes.size
              - if user_signed_in?
                - if (@pin.user == current_user)
                  = link_to "Edit", edit_pin_path, class: "btn btn-default"
                  = link_to "Delete", pin_path, method: :delete, data: { confirm: "are you sure?"}, class: "btn btn-default"